name: Say Hello World
on:
  push:

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: repository-settings/app@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
